### ISSUE TITLE
Testing auxdisp driver

### ISSUE THREAD

**Issue by francescodiotalevi** [andreamerello/linux-zynq-stable#1]
Hi Andrea,
can you try to compile this [driver](https://github.com/francescodiotalevi/projects/tree/master/P2015_01_CER/sw/drivers/auxdisp) on your stable kernel? It is the linux driver able to manage the auxdisp fpga module for CER.
Thank you so much.

**Comment by andreamerello** [comment]
Fails, due to missing Xilinx DMA driver. I'm going to add it to my stable kernel tree.

auxdisp.c:21:35: fatal error: linux/amba/xilinx_dma.h: No such file or directory

**Comment by francescodiotalevi** [comment]
You are right Andrea...
for this driver I used xilinx_dma in the programmable logic of dma. I also used the processing system GPIO to reset the USB phy.
If it can be useful for you, this is the snippet of device tree related to programmable logic that I'm referring to.

```
/ {
        amba_pl: amba_pl {
                #address-cells = <1>;
                #size-cells = <1>;
                compatible = "simple-bus";
                ranges ;
                auxdisp_0: auxdisp@43c00000 {
                        compatible = "iit,auxdisp-1.0";
                        interrupt-parent = <&intc>;
                        interrupts = <0 31 4>;
                        reg = <0x43c00000 0x10000>;
                        xlnx,hor-module = <0x5>;
                        xlnx,log2numlines = <0x4>;
                        xlnx,numlines = <0x10>;
                        xlnx,numrows = <0x2>;
                        /* 109 = 54(offset default for gpio) + 55 */
                        auxdisp-reset = <&gpio0 109 1>;
                };
                axi_dma_0: dma@40400000 {
                        compatible = "xlnx,axi-dma";
                        interrupt-parent = <&intc>;
                        interrupts = <0 29 4>;
                        reg = <0x40400000 0x10000>;
                        xlnx,include-sg ;
                        dma-channel@40400000 {
                                compatible = "xlnx,axi-dma-mm2s-channel";
                                interrupts = <0 29 4>;
                                xlnx,datawidth = <0x20>;
                                xlnx,device-id = <0x0>;
                        };
                };
        };
};
```

Thanks. Francesco.

**Comment by andreamerello** [comment]
Please give a look to my branch 
linux-4.1.13-P2015_01_CER
It does include both Xilinx DMA driver and the PL DT (zynq-zturn-myir.dts)

I'm going to send you a pull request  in order to make your driver compile against this branch

**Comment by andreamerello** [comment]
I have an updated CER driver, that compiles against latest DMA driver in my stable branch. Could you please provide me a BOOT.bin with proper U-boot and FPGA stream ?

**Comment by francescodiotalevi** [comment]
Hi, attached the BOOT.bin zipped file. It works on hardware.
[BOOT.bin.zip](https://github.com/andreamerello/linux-zynq-stable/files/105211/BOOT.bin.zip)
I attach also the image.c and a bitmap to test it.
[prg_to_test.zip](https://github.com/andreamerello/linux-zynq-stable/files/105232/prg_to_test.zip)
Even if the best should be to try it in the "official" hw setup ;-)
