### ISSUE TITLE
Missing shutdown button for MYIR

### ISSUE THREAD

**Issue by claudiolorini** [andreamerello/linux-zynq-stable#12]
Bella!
could you please add in the MYIR dts the parts to add the powerdown button? 
should be something like:

```
gpio-keys {
    compatible = "gpio-keys";
    #address-cells = <0x1>;
    #size-cells = <0x0>;
    autorepeat;

    // User Switch used as 'shut down'
    button_power_at_0 {
        label="Power button virt";
        linux,code = <0x74>;
        // EMIO50, active low
        gpios = <&gpio0 50 1>;
        autorepeat;
        debounce-interval = <1000>; 
    };
};
```

C.

**Comment by francescodiotalevi** [comment]
Andrea,
please add a line as follows:

just after the line "autorepeat";
you should add the following line:
debounce-interval = <3000>; in such a ways to wait 3 seconds before to effectvely have the system halting.

**Comment by andreamerello** [comment]
Now works. closing
