### ISSUE TITLE
USB WiFi is not working [branch: linux-4.1.13-zynq]

### ISSUE THREAD

**Issue by claudiolorini** [andreamerello/linux-zynq-stable#3]
Bella lì!
I have some problem with with the USB WiFi (RTL8188CUS) with 
current branch (linux-4.1.13-zynq) that was ok with some previous 
kernel/devicetree/FPGA.

The easy debug steps have been done:
- USB seems to be up and running:

lsusb 
Bus 001 Device 003: ID 0bda:8176 Realtek Semiconductor Corp. RTL8188CUS 802.11n WLAN Adapter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
- Binary firmware has been added:

ls -lA /lib/firmware/rtlwifi/
total 312
-rw-r--r-- 1 machinekit machinekit  13540 Jan  1  1970 rtl8192cfw.bin
-rw-r--r-- 1 machinekit machinekit  14800 Jan  1  1970 rtl8192cfwU_B.bin
-rw-r--r-- 1 machinekit machinekit  14818 Jan  1  1970 rtl8192cfwU.bin
-rw-r--r-- 1 machinekit machinekit  16014 Jan  1  1970 rtl8192cufw.bin
-rw-r--r-- 1 machinekit machinekit  16116 Jan  1  1970 rtl8192cufw_TMSC.bin
-rw-r--r-- 1 machinekit machinekit  20526 Jan  1  1970 rtl8192defw.bin
-rw-r--r-- 1 machinekit machinekit  88856 Jan  1  1970 rtl8192sefw.bin
-rw-r--r-- 1 machinekit machinekit 122328 Jan  1  1970 rtl8712u.bin
- No kernel error messages at boot time:

dmesg
...
[   16.563913] usb 1-1: new high-speed USB device number 3 using ci_hdrc
[   16.685879] usb 1-1: New USB device found, idVendor=0bda, idProduct=8176
[   16.692606] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   16.699776] usb 1-1: Product: 802.11n WLAN Adapter
[   16.704587] usb 1-1: Manufacturer: Realtek
[   16.708716] usb 1-1: SerialNumber: 00e04c000001
...
- but the wlan0 interface doesn't appear!

ifconfig -a
can0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          NOARP  MTU:16  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:10 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:21 

eth0      Link encap:Ethernet  HWaddr 00:0a:35:00:01:29  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:24 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:656 (656.0 B)  TX bytes:7308 (7.1 KiB)
          Interrupt:143 Base address:0xb000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:224 (224.0 B)  TX bytes:224 (224.0 B)

**any brilliant idea?** 
C.

**Comment by andreamerello** [comment]
Bella Claudio!

If nothing else appears in the log, then It seems that the WiFi driver does not come in at all !

All the messages you are seeing are fired when USB layer recognizing your dongle; they would appear even plugging a completely unsupported dongle for which no driver exists ! :)

I checked our defconfig, and I find out that I have configured this WiFi driver to be build as a module :/

..So you need either to build kernel modules and take care of loading it, or to change the kernel config in order embed this driver in the kernel image..

As you know, my original intention was to enable the in-kernel build of this driver in our defconfig.. I wanted also to enable module build for another bunch of WiFi drivers covering dongles that I have here, or that I know are quite common.. Probably, doing that, I hit also the rtl8188 driver by mistake. :/

**Comment by claudiolorini** [comment]
...yes, i've seen the config with xconfig and the RTL8188 is not enabled.
When I try to enable it doesn't let me!  the little s*it must have some dependency i can not find!
I've also seen that in the same zone there are some drivers that can only be marked 'build as module'
if you click it it only gives you the small dot or an empty square, no check sign... does it sound right 
to you?

**Comment by andreamerello** [comment]
Hopefully fixed in my last commit 777ac0a99e673c1c1f321fcac44da029189eb66a  
(No HW here to test it). Plase give it a try and let me know :)

**Comment by claudiolorini** [comment]
just tested: i'm on-line!
closing.
