### ISSUE TITLE
Missing branch for the P2016_02_M4BP project

### ISSUE THREAD

**Issue by claudiolorini** [andreamerello/linux-zynq-stable#9]
Bella li!
up to now we are missing a branch for the integration (dts/drivers) of the devices in the M4BP project:
- gcpr 
- temperature sensors
- ADCs
- RTC
- ttyPS1 Serial (?)

when you're done i can try to cook a kernel, patch it RT and see what happens...

**Comment by andreamerello** [comment]
Done.Closing
